name: SonarQube

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        args: >
          /d:sonar.organization=dsmithson-github
          /d:sonar.projectKey=dsmithson_KnightwareCore
          /o:"dsmithson-github"
